-- MySQL Script generated by MySQL Workbench
-- Sat Aug 29 23:06:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema siga
-- -----------------------------------------------------
-- tcc-puc

-- -----------------------------------------------------
-- Schema siga
--
-- tcc-puc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siga` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `siga` ;

-- -----------------------------------------------------
-- Table `siga`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`usuario` ;

CREATE TABLE IF NOT EXISTS `siga`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `identidade` VARCHAR(11) NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(60) NULL,
  `celular` DECIMAL(9) NULL,
  `status` VARCHAR(1) NULL,
  `senha` VARCHAR(256) NULL,
  `biometria` BLOB(256) NULL,
  `tipo_usuario` VARCHAR(10) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `identidade_UNIQUE` (`identidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`aluno` ;

CREATE TABLE IF NOT EXISTS `siga`.`aluno` (
  `usuario_id_usuario` INT NOT NULL,
  `nascimento` DATE NULL,
  `ferias` VARCHAR(1) NULL,
  `ciente_atraso_pgto` VARCHAR(1) NULL,
  `ciente_exame_expirado` VARCHAR(1) NULL,
  `logradouro` VARCHAR(50) NULL,
  `bairro` VARCHAR(50) NULL,
  `cidade` VARCHAR(50) NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  INDEX `fk_aluno_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`instrutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`instrutor` ;

CREATE TABLE IF NOT EXISTS `siga`.`instrutor` (
  `tipo-aula` VARCHAR(45) NULL,
  `cref` VARCHAR(15) NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_instrutor_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`contrato` ;

CREATE TABLE IF NOT EXISTS `siga`.`contrato` (
  `id_contrato` INT NOT NULL,
  `tipo_plano` VARCHAR(6) NULL,
  `valor` FLOAT NULL,
  `desconto` FLOAT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `pausa_ferias` TINYINT NULL,
  `status` VARCHAR(10) NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_contrato`, `usuario_id_usuario`),
  INDEX `fk_contrato_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_contrato_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `siga`.`pagamento` (
  `id_pagamanto` INT NOT NULL AUTO_INCREMENT,
  `mes_referencia` DATE NULL,
  `valor` FLOAT NULL,
  `data_pagamento` DATE NULL,
  `multa` INT NULL,
  `desconto` INT NULL,
  `valor_pago` FLOAT NULL,
  `meio_pagamento` VARCHAR(10) NULL,
  `status` VARCHAR(10) NULL,
  `contrato_id_contrato` INT NOT NULL,
  PRIMARY KEY (`id_pagamanto`, `contrato_id_contrato`),
  INDEX `fk_taxa_utilizacao_contrato1_idx` (`contrato_id_contrato` ASC) VISIBLE,
  CONSTRAINT `fk_taxa_utilizacao_contrato1`
    FOREIGN KEY (`contrato_id_contrato`)
    REFERENCES `siga`.`contrato` (`id_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`Sala` ;

CREATE TABLE IF NOT EXISTS `siga`.`Sala` (
  `idSala` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `tamanho` VARCHAR(10) NULL,
  `observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`aula` ;

CREATE TABLE IF NOT EXISTS `siga`.`aula` (
  `idaula` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `atividade` VARCHAR(45) NULL,
  `local_sala` VARCHAR(45) NULL,
  `hora_fim` DATE NULL,
  `hora_ini` DATE NULL,
  `dia_semana` VARCHAR(7) NULL,
  `usuario_id_usuario` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`idaula`, `usuario_id_usuario`, `Sala_idSala`),
  INDEX `fk_aula_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_aula_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_aula_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aula_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `siga`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`frequencia` ;

CREATE TABLE IF NOT EXISTS `siga`.`frequencia` (
  `idfrequencia` INT NOT NULL,
  `data_presenca` DATETIME NULL,
  `usuario_id_usuario` INT NOT NULL,
  `aula_idaula` INT NOT NULL,
  `aula_usuario_id_usuario` INT NOT NULL,
  `aula_Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`idfrequencia`, `usuario_id_usuario`, `aula_idaula`, `aula_usuario_id_usuario`, `aula_Sala_idSala`),
  INDEX `fk_frequencia_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_frequencia_aula1_idx` (`aula_idaula` ASC, `aula_usuario_id_usuario` ASC, `aula_Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_frequencia_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_frequencia_aula1`
    FOREIGN KEY (`aula_idaula` , `aula_usuario_id_usuario` , `aula_Sala_idSala`)
    REFERENCES `siga`.`aula` (`idaula` , `usuario_id_usuario` , `Sala_idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`avaliacao_medica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`avaliacao_medica` ;

CREATE TABLE IF NOT EXISTS `siga`.`avaliacao_medica` (
  `idavaliacao_medica` INT NOT NULL,
  `data` DATE NULL,
  `validade` DATE NULL,
  `aluno_usuario_id_usuario` INT NOT NULL,
  `instrutor_usuario_matricula` INT NOT NULL,
  `observacao` VARCHAR(100) NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`idavaliacao_medica`, `aluno_usuario_id_usuario`, `instrutor_usuario_matricula`, `usuario_id_usuario`),
  INDEX `fk_avaliacao_medica_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_medica_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`anaminese`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`anaminese` ;

CREATE TABLE IF NOT EXISTS `siga`.`anaminese` (
  `idanaminese` INT NOT NULL,
  `alergia` VARCHAR(1) NULL,
  `uso_alcool` VARCHAR(1) NULL,
  `fumante` VARCHAR(1) NULL,
  `hipertenso` VARCHAR(1) NULL,
  `diabetes` VARCHAR(1) NULL,
  `avaliacao_medica_idavaliacao_medica` INT NOT NULL,
  `avaliacao_medica_aluno_usuario_id_usuario` INT NOT NULL,
  `avaliacao_medica_instrutor_usuario_matricula` INT NOT NULL,
  PRIMARY KEY (`idanaminese`, `avaliacao_medica_idavaliacao_medica`, `avaliacao_medica_aluno_usuario_id_usuario`, `avaliacao_medica_instrutor_usuario_matricula`),
  INDEX `fk_anaminese_avaliacao_medica1_idx` (`avaliacao_medica_idavaliacao_medica` ASC, `avaliacao_medica_aluno_usuario_id_usuario` ASC, `avaliacao_medica_instrutor_usuario_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_anaminese_avaliacao_medica1`
    FOREIGN KEY (`avaliacao_medica_idavaliacao_medica` , `avaliacao_medica_aluno_usuario_id_usuario` , `avaliacao_medica_instrutor_usuario_matricula`)
    REFERENCES `siga`.`avaliacao_medica` (`idavaliacao_medica` , `aluno_usuario_id_usuario` , `instrutor_usuario_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`dobras_cutaneas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`dobras_cutaneas` ;

CREATE TABLE IF NOT EXISTS `siga`.`dobras_cutaneas` (
  `iddobras_cutaneas` INT NOT NULL,
  `triciptral` INT NULL,
  `subescapular` INT NULL,
  `biciptal` INT NULL,
  `axilar_media` INT NULL,
  `supra_iliaca` INT NULL,
  `toraxica` INT NULL,
  `coxa` INT NULL,
  `abdominal` INT NULL,
  `panturrilha_medial` INT NULL,
  `avaliacao_medica_idavaliacao_medica` INT NOT NULL,
  `avaliacao_medica_aluno_usuario_id_usuario` INT NOT NULL,
  `avaliacao_medica_instrutor_usuario_matricula` INT NOT NULL,
  PRIMARY KEY (`iddobras_cutaneas`, `avaliacao_medica_idavaliacao_medica`, `avaliacao_medica_aluno_usuario_id_usuario`, `avaliacao_medica_instrutor_usuario_matricula`),
  INDEX `fk_dobras_cutaneas_avaliacao_medica1_idx` (`avaliacao_medica_idavaliacao_medica` ASC, `avaliacao_medica_aluno_usuario_id_usuario` ASC, `avaliacao_medica_instrutor_usuario_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_dobras_cutaneas_avaliacao_medica1`
    FOREIGN KEY (`avaliacao_medica_idavaliacao_medica` , `avaliacao_medica_aluno_usuario_id_usuario` , `avaliacao_medica_instrutor_usuario_matricula`)
    REFERENCES `siga`.`avaliacao_medica` (`idavaliacao_medica` , `aluno_usuario_id_usuario` , `instrutor_usuario_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = ndbcluster;


-- -----------------------------------------------------
-- Table `siga`.`ferias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`ferias` ;

CREATE TABLE IF NOT EXISTS `siga`.`ferias` (
  `id_ferias` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `dias` INT NOT NULL,
  `ano_referencia` DATE NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_ferias`, `usuario_id_usuario`),
  INDEX `fk_ferias_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_ferias_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`exame_ergometrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`exame_ergometrico` ;

CREATE TABLE IF NOT EXISTS `siga`.`exame_ergometrico` (
  `id_exame_ergometrico` INT NOT NULL,
  `pressao_arterial` VARCHAR(7) NULL,
  `freq_cardiaca` INT NULL,
  `avaliacao_medica_idavaliacao_medica` INT UNSIGNED NOT NULL,
  `avaliacao_medica_aluno_usuario_id_usuario` INT UNSIGNED NOT NULL,
  `avaliacao_medica_instrutor_usuario_matricula` INT NOT NULL,
  PRIMARY KEY (`id_exame_ergometrico`, `avaliacao_medica_idavaliacao_medica`, `avaliacao_medica_aluno_usuario_id_usuario`, `avaliacao_medica_instrutor_usuario_matricula`),
  INDEX `fk_exame_ergometrico_avaliacao_medica1_idx` (`avaliacao_medica_idavaliacao_medica` ASC, `avaliacao_medica_aluno_usuario_id_usuario` ASC, `avaliacao_medica_instrutor_usuario_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_exame_ergometrico_avaliacao_medica1`
    FOREIGN KEY (`avaliacao_medica_idavaliacao_medica` , `avaliacao_medica_aluno_usuario_id_usuario` , `avaliacao_medica_instrutor_usuario_matricula`)
    REFERENCES `siga`.`avaliacao_medica` (`idavaliacao_medica` , `aluno_usuario_id_usuario` , `instrutor_usuario_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`Recepcionista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`Recepcionista` ;

CREATE TABLE IF NOT EXISTS `siga`.`Recepcionista` (
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_Recepcionista_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siga`.`fisioterapeuta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siga`.`fisioterapeuta` ;

CREATE TABLE IF NOT EXISTS `siga`.`fisioterapeuta` (
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_fisioterapeuta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `siga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
